### ISSUE TITLE
Data Seeding

### ISSUE THREAD

**Issue by iamjonjackson** [IacobM94/RoomBookingApp#12]
- [x] Rooms
- [ ] Bookings
- [x] Users
- [x] Roles

**Comment by iamjonjackson** [comment]
![image](https://user-images.githubusercontent.com/5783108/192318213-92001736-6be2-4e7b-a97e-13ba3c255260.png)

Rooms seeded (working!)

**Comment by LewisBeane** [comment]
![image](https://user-images.githubusercontent.com/112859792/193578353-ad18b12f-fcec-4d36-8017-860f5dd7d042.png)
![image](https://user-images.githubusercontent.com/112859792/193578476-953a79ea-19b5-4700-acca-439cbf20ba20.png)
![image](https://user-images.githubusercontent.com/112859792/193578524-4f3b57c9-058c-49fa-abe2-646bca17dacd.png)
